# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          lfs: "true"
          fetch-depth: 0
          token: ${{ secrets.PAT || secrets.GITHUB_TOKEN }}
          
      - name: Configure Git
        shell: bash
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Sync develop with main
        shell: bash
        run: |
          # Checkout develop branch
          git checkout develop
          git pull origin develop

          # Merge main into develop with no fast-forward to preserve history
          git merge --no-ff origin/main -m "Merge main into develop after the creation of release"

          # Push changes to develop branch
          git push origin develop
